/**
 * Maps Train Describer berths to a position on our network.
 *
 * Network Rail's TD feed reports which *berth* a train is in, but there is no
 * open dataset of berth coordinates — so (exactly like Traksy / OpenTrainTimes)
 * we hand-map each berth onto a line. A berth's position is given as a line id
 * plus `t` (0..1 along that line's spline).
 *
 * Two sources of berths:
 *  1. DEMO berths — generated to match the server's replay mode, so the whole
 *     pipeline works with no credentials.
 *  2. REAL berths — added to REAL_BERTHS once discovered from the live feed
 *     (run the server with CAPTURE=1, then map the IDs from
 *     server/data/observed-berths.json onto lines here).
 */
import { LINES, LINE_MILEAGES } from "./network";
import { project } from "./geo";
import { nearestOnLines, mileageToT } from "./lineCurves";
import { osGridToLatLng } from "./osgb";
import generatedBerthCoords from "./berthCoordinates.json";
import type { LatLng } from "./types";

/** `dir` is the known travel direction at this berth, where the source data
 *  records it (SMART splits berth steps into down/up): 1 = increasing t,
 *  -1 = decreasing. Optional — berths without it keep inferred direction.
 *  `crs`/`platform`: station + platform the berth stands at, where known —
 *  lets the renderer park the train on the modelled platform lane. */
export type BerthPos = { lineId: string; t: number; dir?: 1 | -1; crs?: string; platform?: string };

const berths = new Map<string, BerthPos>();
const key = (area: string, berth: string) => `${area}:${berth}`;

// --- 1. DEMO berths (must match server/lib/replay.js) ---
const DEMO_PREFIX: Record<string, string> = {
  exmouth: "EXM",
  "newton-abbot": "NAB",
  paignton: "PAI",
  taunton: "TAU",
};
const DEMO_K = 10;
// Replay-mode demo: each line's first berth is at Exeter St David's, so give it
// a platform — demo trains then park on the modelled platform lanes exactly
// like live ones, with no credentials needed.
const DEMO_EXD_PLATFORM: Record<string, string> = {
  "newton-abbot": "4",
  taunton: "5",
  exmouth: "1",
  paignton: "6",
};
for (const line of LINES) {
  const prefix = DEMO_PREFIX[line.id];
  if (!prefix) continue;
  // Position the demo berths through the mileage engine: spread them evenly in
  // *miles* between the line's end stations, then convert to t. This exercises
  // the precise-positioning path end-to-end and spaces the demo trains by real
  // geography. Falls back to even t if a line has no mileage data.
  const miles = LINE_MILEAGES[line.id];
  for (let i = 0; i < DEMO_K; i++) {
    const f = i / (DEMO_K - 1);
    const id = `${prefix}${String(i + 1).padStart(2, "0")}`;
    const t = miles
      ? mileageToT(line.id, miles[0] + (miles[miles.length - 1] - miles[0]) * f)
      : f;
    const atExd = i === 0 && line.stops[0] === "EXD";
    berths.set(key("DEMO", id), {
      lineId: line.id,
      t,
      ...(atExd ? { crs: "EXD", platform: DEMO_EXD_PLATFORM[line.id] } : {}),
    });
  }
}

// --- 2. REAL berths (fill in from captured live data) ---
// Example once you know the IDs (area "SW" is the South West signalling area):
//   ["SW:0123", { lineId: "newton-abbot", t: 0.12 }],
const REAL_BERTHS: [string, BerthPos][] = [
  // [key("SW", "XXXX"), { lineId: "...", t: 0.0 }],
];
for (const [k, pos] of REAL_BERTHS) berths.set(k, pos);

/** Look up a berth's line position, or null if we haven't mapped it yet. */
export function berthPosition(area: string, berth: string): BerthPos | null {
  return berths.get(key(area, berth)) ?? null;
}

// --- 3. REAL berth COORDINATES (the precise path) ---
/**
 * If you can get real berth/signal coordinates, drop them here and trains are
 * placed at their exact positions (no hand-mapping to lines needed). Supply
 * either WGS84 lat/lng OR OS National Grid easting/northing — both work.
 *
 *   { area: "SW", berth: "0123", lat: 50.5290, lng: -3.6000 }
 *   { area: "SW", berth: "0125", easting: 286000, northing: 71500 }
 */
type CoordEntry = {
  area: string;
  berth: string;
  lat?: number;
  lng?: number;
  easting?: number;
  northing?: number;
  /** Platform at this berth's location, from SMART (e.g. "1".."6" at EXD). */
  platform?: string;
};

const BERTH_COORDS: CoordEntry[] = [
  // Generated by server/scripts/buildBerthCoords.js from Network Rail open data.
  ...(generatedBerthCoords as CoordEntry[]),
  // Add hand-tuned / OS-grid overrides below.
];

/** area:berth → exact lat/lng plus the nearest line (for colour + HUD). */
const coords = new Map<
  string,
  { ll: LatLng; lineId: string; t: number; platform?: string }
>();
for (const c of BERTH_COORDS) {
  let ll: LatLng | null = null;
  if (typeof c.lat === "number" && typeof c.lng === "number") {
    ll = { lat: c.lat, lng: c.lng };
  } else if (typeof c.easting === "number" && typeof c.northing === "number") {
    ll = osGridToLatLng(c.easting, c.northing);
  }
  if (!ll) continue;
  const near = nearestOnLines(project(ll));
  coords.set(key(c.area, c.berth), { ll, lineId: near.lineId, t: near.t, platform: c.platform });
}

/** Exact coordinate for a berth (with nearest line), or null if none supplied. */
export function berthLatLng(
  area: string,
  berth: string,
): { ll: LatLng; lineId: string; t: number; platform?: string } | null {
  return coords.get(key(area, berth)) ?? null;
}
